name: dpo-finance
channels:
  - conda-forge
  - pytorch
  
dependencies:
  - python>=3.9
  - pytorch
  - pytorch-lightning
  - numpy
  - pandas
  - scikit-learn
  - tensorboardX
  - hydra-core
  - optuna
  - yfinance
  - wandb
  - pyarrow
  - pip
  - pip:
      - finta
  
