# Default configuration for DPO‑Finance training

dataset:
  pairs_file: data/pairs.parquet
  prices_dir: data/raw
  lookback: 30
  batch_size: 256
  num_workers: 4
  val_fraction: 0.1

model:
  input_dim: 29
  hidden_sizes: [256, 256]

train:
  lr: 3.0e-4
  kl_coeff: 0.02

trainer:
  max_epochs: 30
  accelerator: auto
  devices: 1
  log_every_n_steps: 50
  precision: 32

logger:
  use_tb: true              # set false to disable TensorBoard
  experiment_name: dpo
