# Default configuration for DPO‑Finance training

# -------------------------------- Dataset --------------------------------
dataset:
  pairs_file: data/pairs.parquet   # Parquet from make_pairs.py
  prices_dir: data/raw            # Directory with OHLCV CSVs
  lookback: 30                    # Window length (days) → input_dim = lookback‑1
  batch_size: 256
  num_workers: 4
  val_fraction: 0.1

# --------------------------------- Model ---------------------------------
model:
  input_dim: 29                   # lookback‑1
  hidden_sizes: [256, 256]

# -------------------------------- Training -------------------------------
train:
  lr: 3.0e-4
  kl_coeff: 0.02                 # Set to 0 to disable KL regularization

# ------------------------------- PyTorch‑Lightning ------------------------
trainer:
  max_epochs: 30
  accelerator: auto             # "gpu" if available
  devices: 1
  log_every_n_steps: 50
  precision: 32
